/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package it.gestoreattivita.bff.rs.dto.attivita;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class InsertAttivitaRequestDto extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3932988940787602507L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InsertAttivitaRequestDto\",\"namespace\":\"it.gestoreattivita.bff.rs.dto.attivita\",\"fields\":[{\"name\":\"alias\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"lavorata\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"attivitaPadre\",\"type\":[\"null\",\"long\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<InsertAttivitaRequestDto> ENCODER =
      new BinaryMessageEncoder<InsertAttivitaRequestDto>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<InsertAttivitaRequestDto> DECODER =
      new BinaryMessageDecoder<InsertAttivitaRequestDto>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<InsertAttivitaRequestDto> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<InsertAttivitaRequestDto> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<InsertAttivitaRequestDto> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<InsertAttivitaRequestDto>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this InsertAttivitaRequestDto to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a InsertAttivitaRequestDto from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a InsertAttivitaRequestDto instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static InsertAttivitaRequestDto fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String alias;
   private java.lang.String lavorata;
   private java.lang.Long attivitaPadre;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public InsertAttivitaRequestDto() {}

  /**
   * All-args constructor.
   * @param alias The new value for alias
   * @param lavorata The new value for lavorata
   * @param attivitaPadre The new value for attivitaPadre
   */
  public InsertAttivitaRequestDto(java.lang.String alias, java.lang.String lavorata, java.lang.Long attivitaPadre) {
    this.alias = alias;
    this.lavorata = lavorata;
    this.attivitaPadre = attivitaPadre;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return alias;
    case 1: return lavorata;
    case 2: return attivitaPadre;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: alias = value$ != null ? value$.toString() : null; break;
    case 1: lavorata = value$ != null ? value$.toString() : null; break;
    case 2: attivitaPadre = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'alias' field.
   * @return The value of the 'alias' field.
   */
  public java.lang.String getAlias() {
    return alias;
  }


  /**
   * Sets the value of the 'alias' field.
   * @param value the value to set.
   */
  public void setAlias(java.lang.String value) {
    this.alias = value;
  }

  /**
   * Gets the value of the 'lavorata' field.
   * @return The value of the 'lavorata' field.
   */
  public java.lang.String getLavorata() {
    return lavorata;
  }


  /**
   * Sets the value of the 'lavorata' field.
   * @param value the value to set.
   */
  public void setLavorata(java.lang.String value) {
    this.lavorata = value;
  }

  /**
   * Gets the value of the 'attivitaPadre' field.
   * @return The value of the 'attivitaPadre' field.
   */
  public java.lang.Long getAttivitaPadre() {
    return attivitaPadre;
  }


  /**
   * Sets the value of the 'attivitaPadre' field.
   * @param value the value to set.
   */
  public void setAttivitaPadre(java.lang.Long value) {
    this.attivitaPadre = value;
  }

  /**
   * Creates a new InsertAttivitaRequestDto RecordBuilder.
   * @return A new InsertAttivitaRequestDto RecordBuilder
   */
  public static it.gestoreattivita.bff.rs.dto.attivita.InsertAttivitaRequestDto.Builder newBuilder() {
    return new it.gestoreattivita.bff.rs.dto.attivita.InsertAttivitaRequestDto.Builder();
  }

  /**
   * Creates a new InsertAttivitaRequestDto RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new InsertAttivitaRequestDto RecordBuilder
   */
  public static it.gestoreattivita.bff.rs.dto.attivita.InsertAttivitaRequestDto.Builder newBuilder(it.gestoreattivita.bff.rs.dto.attivita.InsertAttivitaRequestDto.Builder other) {
    if (other == null) {
      return new it.gestoreattivita.bff.rs.dto.attivita.InsertAttivitaRequestDto.Builder();
    } else {
      return new it.gestoreattivita.bff.rs.dto.attivita.InsertAttivitaRequestDto.Builder(other);
    }
  }

  /**
   * Creates a new InsertAttivitaRequestDto RecordBuilder by copying an existing InsertAttivitaRequestDto instance.
   * @param other The existing instance to copy.
   * @return A new InsertAttivitaRequestDto RecordBuilder
   */
  public static it.gestoreattivita.bff.rs.dto.attivita.InsertAttivitaRequestDto.Builder newBuilder(it.gestoreattivita.bff.rs.dto.attivita.InsertAttivitaRequestDto other) {
    if (other == null) {
      return new it.gestoreattivita.bff.rs.dto.attivita.InsertAttivitaRequestDto.Builder();
    } else {
      return new it.gestoreattivita.bff.rs.dto.attivita.InsertAttivitaRequestDto.Builder(other);
    }
  }

  /**
   * RecordBuilder for InsertAttivitaRequestDto instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InsertAttivitaRequestDto>
    implements org.apache.avro.data.RecordBuilder<InsertAttivitaRequestDto> {

    private java.lang.String alias;
    private java.lang.String lavorata;
    private java.lang.Long attivitaPadre;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(it.gestoreattivita.bff.rs.dto.attivita.InsertAttivitaRequestDto.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.alias)) {
        this.alias = data().deepCopy(fields()[0].schema(), other.alias);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.lavorata)) {
        this.lavorata = data().deepCopy(fields()[1].schema(), other.lavorata);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.attivitaPadre)) {
        this.attivitaPadre = data().deepCopy(fields()[2].schema(), other.attivitaPadre);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing InsertAttivitaRequestDto instance
     * @param other The existing instance to copy.
     */
    private Builder(it.gestoreattivita.bff.rs.dto.attivita.InsertAttivitaRequestDto other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.alias)) {
        this.alias = data().deepCopy(fields()[0].schema(), other.alias);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lavorata)) {
        this.lavorata = data().deepCopy(fields()[1].schema(), other.lavorata);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.attivitaPadre)) {
        this.attivitaPadre = data().deepCopy(fields()[2].schema(), other.attivitaPadre);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'alias' field.
      * @return The value.
      */
    public java.lang.String getAlias() {
      return alias;
    }


    /**
      * Sets the value of the 'alias' field.
      * @param value The value of 'alias'.
      * @return This builder.
      */
    public it.gestoreattivita.bff.rs.dto.attivita.InsertAttivitaRequestDto.Builder setAlias(java.lang.String value) {
      validate(fields()[0], value);
      this.alias = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'alias' field has been set.
      * @return True if the 'alias' field has been set, false otherwise.
      */
    public boolean hasAlias() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'alias' field.
      * @return This builder.
      */
    public it.gestoreattivita.bff.rs.dto.attivita.InsertAttivitaRequestDto.Builder clearAlias() {
      alias = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'lavorata' field.
      * @return The value.
      */
    public java.lang.String getLavorata() {
      return lavorata;
    }


    /**
      * Sets the value of the 'lavorata' field.
      * @param value The value of 'lavorata'.
      * @return This builder.
      */
    public it.gestoreattivita.bff.rs.dto.attivita.InsertAttivitaRequestDto.Builder setLavorata(java.lang.String value) {
      validate(fields()[1], value);
      this.lavorata = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'lavorata' field has been set.
      * @return True if the 'lavorata' field has been set, false otherwise.
      */
    public boolean hasLavorata() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'lavorata' field.
      * @return This builder.
      */
    public it.gestoreattivita.bff.rs.dto.attivita.InsertAttivitaRequestDto.Builder clearLavorata() {
      lavorata = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'attivitaPadre' field.
      * @return The value.
      */
    public java.lang.Long getAttivitaPadre() {
      return attivitaPadre;
    }


    /**
      * Sets the value of the 'attivitaPadre' field.
      * @param value The value of 'attivitaPadre'.
      * @return This builder.
      */
    public it.gestoreattivita.bff.rs.dto.attivita.InsertAttivitaRequestDto.Builder setAttivitaPadre(java.lang.Long value) {
      validate(fields()[2], value);
      this.attivitaPadre = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'attivitaPadre' field has been set.
      * @return True if the 'attivitaPadre' field has been set, false otherwise.
      */
    public boolean hasAttivitaPadre() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'attivitaPadre' field.
      * @return This builder.
      */
    public it.gestoreattivita.bff.rs.dto.attivita.InsertAttivitaRequestDto.Builder clearAttivitaPadre() {
      attivitaPadre = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public InsertAttivitaRequestDto build() {
      try {
        InsertAttivitaRequestDto record = new InsertAttivitaRequestDto();
        record.alias = fieldSetFlags()[0] ? this.alias : (java.lang.String) defaultValue(fields()[0]);
        record.lavorata = fieldSetFlags()[1] ? this.lavorata : (java.lang.String) defaultValue(fields()[1]);
        record.attivitaPadre = fieldSetFlags()[2] ? this.attivitaPadre : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<InsertAttivitaRequestDto>
    WRITER$ = (org.apache.avro.io.DatumWriter<InsertAttivitaRequestDto>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<InsertAttivitaRequestDto>
    READER$ = (org.apache.avro.io.DatumReader<InsertAttivitaRequestDto>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.alias);

    if (this.lavorata == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.lavorata);
    }

    if (this.attivitaPadre == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.attivitaPadre);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.alias = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.lavorata = null;
      } else {
        this.lavorata = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.attivitaPadre = null;
      } else {
        this.attivitaPadre = in.readLong();
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.alias = in.readString();
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.lavorata = null;
          } else {
            this.lavorata = in.readString();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.attivitaPadre = null;
          } else {
            this.attivitaPadre = in.readLong();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










