/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package it.gestoreattivita.bff.rs.dto.attivita;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PageAttivitaDto extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6120996262712598409L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PageAttivitaDto\",\"namespace\":\"it.gestoreattivita.bff.rs.dto.attivita\",\"fields\":[{\"name\":\"page\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"items\",\"type\":[\"null\",\"int\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PageAttivitaDto> ENCODER =
      new BinaryMessageEncoder<PageAttivitaDto>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PageAttivitaDto> DECODER =
      new BinaryMessageDecoder<PageAttivitaDto>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PageAttivitaDto> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PageAttivitaDto> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PageAttivitaDto> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PageAttivitaDto>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PageAttivitaDto to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PageAttivitaDto from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PageAttivitaDto instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PageAttivitaDto fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.Integer page;
   private java.lang.Integer items;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PageAttivitaDto() {}

  /**
   * All-args constructor.
   * @param page The new value for page
   * @param items The new value for items
   */
  public PageAttivitaDto(java.lang.Integer page, java.lang.Integer items) {
    this.page = page;
    this.items = items;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return page;
    case 1: return items;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: page = (java.lang.Integer)value$; break;
    case 1: items = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'page' field.
   * @return The value of the 'page' field.
   */
  public java.lang.Integer getPage() {
    return page;
  }


  /**
   * Sets the value of the 'page' field.
   * @param value the value to set.
   */
  public void setPage(java.lang.Integer value) {
    this.page = value;
  }

  /**
   * Gets the value of the 'items' field.
   * @return The value of the 'items' field.
   */
  public java.lang.Integer getItems() {
    return items;
  }


  /**
   * Sets the value of the 'items' field.
   * @param value the value to set.
   */
  public void setItems(java.lang.Integer value) {
    this.items = value;
  }

  /**
   * Creates a new PageAttivitaDto RecordBuilder.
   * @return A new PageAttivitaDto RecordBuilder
   */
  public static it.gestoreattivita.bff.rs.dto.attivita.PageAttivitaDto.Builder newBuilder() {
    return new it.gestoreattivita.bff.rs.dto.attivita.PageAttivitaDto.Builder();
  }

  /**
   * Creates a new PageAttivitaDto RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PageAttivitaDto RecordBuilder
   */
  public static it.gestoreattivita.bff.rs.dto.attivita.PageAttivitaDto.Builder newBuilder(it.gestoreattivita.bff.rs.dto.attivita.PageAttivitaDto.Builder other) {
    if (other == null) {
      return new it.gestoreattivita.bff.rs.dto.attivita.PageAttivitaDto.Builder();
    } else {
      return new it.gestoreattivita.bff.rs.dto.attivita.PageAttivitaDto.Builder(other);
    }
  }

  /**
   * Creates a new PageAttivitaDto RecordBuilder by copying an existing PageAttivitaDto instance.
   * @param other The existing instance to copy.
   * @return A new PageAttivitaDto RecordBuilder
   */
  public static it.gestoreattivita.bff.rs.dto.attivita.PageAttivitaDto.Builder newBuilder(it.gestoreattivita.bff.rs.dto.attivita.PageAttivitaDto other) {
    if (other == null) {
      return new it.gestoreattivita.bff.rs.dto.attivita.PageAttivitaDto.Builder();
    } else {
      return new it.gestoreattivita.bff.rs.dto.attivita.PageAttivitaDto.Builder(other);
    }
  }

  /**
   * RecordBuilder for PageAttivitaDto instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PageAttivitaDto>
    implements org.apache.avro.data.RecordBuilder<PageAttivitaDto> {

    private java.lang.Integer page;
    private java.lang.Integer items;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(it.gestoreattivita.bff.rs.dto.attivita.PageAttivitaDto.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.page)) {
        this.page = data().deepCopy(fields()[0].schema(), other.page);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.items)) {
        this.items = data().deepCopy(fields()[1].schema(), other.items);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing PageAttivitaDto instance
     * @param other The existing instance to copy.
     */
    private Builder(it.gestoreattivita.bff.rs.dto.attivita.PageAttivitaDto other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.page)) {
        this.page = data().deepCopy(fields()[0].schema(), other.page);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.items)) {
        this.items = data().deepCopy(fields()[1].schema(), other.items);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'page' field.
      * @return The value.
      */
    public java.lang.Integer getPage() {
      return page;
    }


    /**
      * Sets the value of the 'page' field.
      * @param value The value of 'page'.
      * @return This builder.
      */
    public it.gestoreattivita.bff.rs.dto.attivita.PageAttivitaDto.Builder setPage(java.lang.Integer value) {
      validate(fields()[0], value);
      this.page = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'page' field has been set.
      * @return True if the 'page' field has been set, false otherwise.
      */
    public boolean hasPage() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'page' field.
      * @return This builder.
      */
    public it.gestoreattivita.bff.rs.dto.attivita.PageAttivitaDto.Builder clearPage() {
      page = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'items' field.
      * @return The value.
      */
    public java.lang.Integer getItems() {
      return items;
    }


    /**
      * Sets the value of the 'items' field.
      * @param value The value of 'items'.
      * @return This builder.
      */
    public it.gestoreattivita.bff.rs.dto.attivita.PageAttivitaDto.Builder setItems(java.lang.Integer value) {
      validate(fields()[1], value);
      this.items = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'items' field has been set.
      * @return True if the 'items' field has been set, false otherwise.
      */
    public boolean hasItems() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'items' field.
      * @return This builder.
      */
    public it.gestoreattivita.bff.rs.dto.attivita.PageAttivitaDto.Builder clearItems() {
      items = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PageAttivitaDto build() {
      try {
        PageAttivitaDto record = new PageAttivitaDto();
        record.page = fieldSetFlags()[0] ? this.page : (java.lang.Integer) defaultValue(fields()[0]);
        record.items = fieldSetFlags()[1] ? this.items : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PageAttivitaDto>
    WRITER$ = (org.apache.avro.io.DatumWriter<PageAttivitaDto>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PageAttivitaDto>
    READER$ = (org.apache.avro.io.DatumReader<PageAttivitaDto>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.page == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.page);
    }

    if (this.items == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.items);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.page = null;
      } else {
        this.page = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.items = null;
      } else {
        this.items = in.readInt();
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.page = null;
          } else {
            this.page = in.readInt();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.items = null;
          } else {
            this.items = in.readInt();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










