/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package it.gestoreattivita.bff.rs.dto.attivita;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PaginatorResponseDto extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1876909523334394959L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PaginatorResponseDto\",\"namespace\":\"it.gestoreattivita.bff.rs.dto.attivita\",\"fields\":[{\"name\":\"totalPages\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"totalElements\",\"type\":[\"null\",\"long\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PaginatorResponseDto> ENCODER =
      new BinaryMessageEncoder<PaginatorResponseDto>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PaginatorResponseDto> DECODER =
      new BinaryMessageDecoder<PaginatorResponseDto>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PaginatorResponseDto> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PaginatorResponseDto> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PaginatorResponseDto> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PaginatorResponseDto>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PaginatorResponseDto to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PaginatorResponseDto from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PaginatorResponseDto instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PaginatorResponseDto fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.Integer totalPages;
   private java.lang.Long totalElements;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PaginatorResponseDto() {}

  /**
   * All-args constructor.
   * @param totalPages The new value for totalPages
   * @param totalElements The new value for totalElements
   */
  public PaginatorResponseDto(java.lang.Integer totalPages, java.lang.Long totalElements) {
    this.totalPages = totalPages;
    this.totalElements = totalElements;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return totalPages;
    case 1: return totalElements;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: totalPages = (java.lang.Integer)value$; break;
    case 1: totalElements = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'totalPages' field.
   * @return The value of the 'totalPages' field.
   */
  public java.lang.Integer getTotalPages() {
    return totalPages;
  }


  /**
   * Sets the value of the 'totalPages' field.
   * @param value the value to set.
   */
  public void setTotalPages(java.lang.Integer value) {
    this.totalPages = value;
  }

  /**
   * Gets the value of the 'totalElements' field.
   * @return The value of the 'totalElements' field.
   */
  public java.lang.Long getTotalElements() {
    return totalElements;
  }


  /**
   * Sets the value of the 'totalElements' field.
   * @param value the value to set.
   */
  public void setTotalElements(java.lang.Long value) {
    this.totalElements = value;
  }

  /**
   * Creates a new PaginatorResponseDto RecordBuilder.
   * @return A new PaginatorResponseDto RecordBuilder
   */
  public static it.gestoreattivita.bff.rs.dto.attivita.PaginatorResponseDto.Builder newBuilder() {
    return new it.gestoreattivita.bff.rs.dto.attivita.PaginatorResponseDto.Builder();
  }

  /**
   * Creates a new PaginatorResponseDto RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PaginatorResponseDto RecordBuilder
   */
  public static it.gestoreattivita.bff.rs.dto.attivita.PaginatorResponseDto.Builder newBuilder(it.gestoreattivita.bff.rs.dto.attivita.PaginatorResponseDto.Builder other) {
    if (other == null) {
      return new it.gestoreattivita.bff.rs.dto.attivita.PaginatorResponseDto.Builder();
    } else {
      return new it.gestoreattivita.bff.rs.dto.attivita.PaginatorResponseDto.Builder(other);
    }
  }

  /**
   * Creates a new PaginatorResponseDto RecordBuilder by copying an existing PaginatorResponseDto instance.
   * @param other The existing instance to copy.
   * @return A new PaginatorResponseDto RecordBuilder
   */
  public static it.gestoreattivita.bff.rs.dto.attivita.PaginatorResponseDto.Builder newBuilder(it.gestoreattivita.bff.rs.dto.attivita.PaginatorResponseDto other) {
    if (other == null) {
      return new it.gestoreattivita.bff.rs.dto.attivita.PaginatorResponseDto.Builder();
    } else {
      return new it.gestoreattivita.bff.rs.dto.attivita.PaginatorResponseDto.Builder(other);
    }
  }

  /**
   * RecordBuilder for PaginatorResponseDto instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PaginatorResponseDto>
    implements org.apache.avro.data.RecordBuilder<PaginatorResponseDto> {

    private java.lang.Integer totalPages;
    private java.lang.Long totalElements;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(it.gestoreattivita.bff.rs.dto.attivita.PaginatorResponseDto.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.totalPages)) {
        this.totalPages = data().deepCopy(fields()[0].schema(), other.totalPages);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.totalElements)) {
        this.totalElements = data().deepCopy(fields()[1].schema(), other.totalElements);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing PaginatorResponseDto instance
     * @param other The existing instance to copy.
     */
    private Builder(it.gestoreattivita.bff.rs.dto.attivita.PaginatorResponseDto other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.totalPages)) {
        this.totalPages = data().deepCopy(fields()[0].schema(), other.totalPages);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.totalElements)) {
        this.totalElements = data().deepCopy(fields()[1].schema(), other.totalElements);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'totalPages' field.
      * @return The value.
      */
    public java.lang.Integer getTotalPages() {
      return totalPages;
    }


    /**
      * Sets the value of the 'totalPages' field.
      * @param value The value of 'totalPages'.
      * @return This builder.
      */
    public it.gestoreattivita.bff.rs.dto.attivita.PaginatorResponseDto.Builder setTotalPages(java.lang.Integer value) {
      validate(fields()[0], value);
      this.totalPages = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'totalPages' field has been set.
      * @return True if the 'totalPages' field has been set, false otherwise.
      */
    public boolean hasTotalPages() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'totalPages' field.
      * @return This builder.
      */
    public it.gestoreattivita.bff.rs.dto.attivita.PaginatorResponseDto.Builder clearTotalPages() {
      totalPages = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalElements' field.
      * @return The value.
      */
    public java.lang.Long getTotalElements() {
      return totalElements;
    }


    /**
      * Sets the value of the 'totalElements' field.
      * @param value The value of 'totalElements'.
      * @return This builder.
      */
    public it.gestoreattivita.bff.rs.dto.attivita.PaginatorResponseDto.Builder setTotalElements(java.lang.Long value) {
      validate(fields()[1], value);
      this.totalElements = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'totalElements' field has been set.
      * @return True if the 'totalElements' field has been set, false otherwise.
      */
    public boolean hasTotalElements() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'totalElements' field.
      * @return This builder.
      */
    public it.gestoreattivita.bff.rs.dto.attivita.PaginatorResponseDto.Builder clearTotalElements() {
      totalElements = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PaginatorResponseDto build() {
      try {
        PaginatorResponseDto record = new PaginatorResponseDto();
        record.totalPages = fieldSetFlags()[0] ? this.totalPages : (java.lang.Integer) defaultValue(fields()[0]);
        record.totalElements = fieldSetFlags()[1] ? this.totalElements : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PaginatorResponseDto>
    WRITER$ = (org.apache.avro.io.DatumWriter<PaginatorResponseDto>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PaginatorResponseDto>
    READER$ = (org.apache.avro.io.DatumReader<PaginatorResponseDto>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.totalPages == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.totalPages);
    }

    if (this.totalElements == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.totalElements);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.totalPages = null;
      } else {
        this.totalPages = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.totalElements = null;
      } else {
        this.totalElements = in.readLong();
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.totalPages = null;
          } else {
            this.totalPages = in.readInt();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.totalElements = null;
          } else {
            this.totalElements = in.readLong();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










